### ISSUE TITLE
Program not showing cloud data.

### ISSUE THREAD

**Issue by Sojiro84** [GMMan/SteamCloudFileManagerLite#13]
Hello,

I tried a few AppID's of games which has Cloud data, but after connecting and refreshing multiple times, I can't get any of the files to show up. I have cloud sync on.

I am wondering if I am doing something wrong or if there is something changed and the program doesn't work at the moment.

I really hope there is a solution to this. I have been looking for a way to delete all my cloud data.

**Comment by GMMan** [comment]
If the game is using auto cloud and not the API, the files won't show up. In that case, check SteamDB for which paths Steam monitors and delete the files while the game is running.

**Comment by Sojiro84** [comment]
Strange. I tried multiple games, old ones, new ones, some from 1 to 2 years ago, but they all don't show any files. I would assume atleast one would show up or is the auto-cloud used by a lot of games?

**Comment by GMMan** [comment]
Could you give a specific one as an example?

**Comment by Sojiro84** [comment]
The old ones I tried was the Half-Life games. A more recent example was 'SpellForce 3: Versus Edition' which came out a few day's ago. Another somewhat recent game is 'The Complex' or 'Tell Me Why' and also 'The Dark Pictures Anthology: Little Hope'.

Just to be sure, I don't need to have any of them installed right? Just give in the AppID, the app should download the files and then I should be able to see them in the list and then delete them?

**Comment by Sojiro84** [comment]
Also, some games give a error.

`---------------------------
Failed to connect
---------------------------
System.Exception: Cannot initialize Steamworks API.
   at SteamCloudFileManager.RemoteStorage..ctor(UInt32 appID) in C:\Users\cyanic\Documents\Visual Studio 2017\Projects\SteamCloudFileManagerLite\SteamCloudFileManager\RemoteStorage.cs:line 57
   at SteamCloudFileManager.RemoteStorage.CreateInstance(UInt32 appID) in C:\Users\cyanic\Documents\Visual Studio 2017\Projects\SteamCloudFileManagerLite\SteamCloudFileManager\RemoteStorage.cs:line 113
   at SteamCloudFileManager.MainForm.connectButton_Click(Object sender, EventArgs e) in C:\Users\cyanic\Documents\Visual Studio 2017\Projects\SteamCloudFileManagerLite\SteamCloudFileManager\MainForm.cs:line 39
---------------------------
OK   
---------------------------
`

**Comment by Sojiro84** [comment]
After some trial and error and looking at the Steam folders, I sometimes see data. What visually seems to work is, enter a appid, close your app. Reopen your app, enter the appid again and then I see the data, I can delete it, but after closing the app (so that the game is not running and the sync happens/should happen) but I don't see the files deleted yet on the steam remote storage page.

Going to bed now, so maybe the steam page needs some time to update.

**Comment by Sojiro84** [comment]
Just check the Steam cloud overview page and the files are still there. Seems like they changed something and your program might not work at the moment.

What I did was entering appid's, like 1 to 10, so that the 'cache' for lack of  a better word is generated. When I am at 10, I go back to 1 and then I can see the files for most of the games. I selected them and deleted them but as said above, the files still remained.

Really frustrating that Valve does not provide a option for us to delete that data and even with a ticket for requesting deletion they wont act on it.

**Comment by GMMan** [comment]
The Complex and The Dark Pictures Anthology: Little Hope appear to be using auto cloud, so would not show any files. The ones you're getting "failed to connect" for are probably apps you don't own which the API will refuse to init. Things seem to work normally on my side.

**Comment by Sojiro84** [comment]
Do you then know why my files are still on the cloud for a game where I saw the files and deleted them? In this case Baldur's Gate 3. Saw the files, deleted them, your program is not showing the files anymore but when I check on https://store.steampowered.com/account/remotestorage I still see all the data there.

Regardless, I do thank you for making a solution on accessing data in the cloud.

**Comment by GMMan** [comment]
Did you wait for the changes to sync up after closing the program?

**Comment by Sojiro84** [comment]
Yeah, when I found out how the program worked, I basically went to baldurs gate, deleted the files, then changed the appid to the second game where I wanted to delete files and then to the third game etc.

Offcourse your program also said that deletion was successful. You think I should wait longer?

**Comment by GMMan** [comment]
If you relaunch the program and it doesn't show up, it's effectively deleted from your storage.

**Comment by KurzedMetal** [comment]
I just wanna say I found the same "issue" when trying to access Last Epoch cloud data. I wanted to reset my offline progress.

And happened like GMMan stated,
I opened SteamCloudFileManagerLite, connected, but saw no files in the list.
But when I deleted the files in AppData folder and closed SteamCloudFileManagerLite it synced all the deleted files and removed them from Steam Cloud.
I also noticed a "steam_autocloud.vdf" file in the directory, suggesting is using the "autocloud" feature that GMMan mentioned.

And I confirmed files were deleted by checking this link: https://store.steampowered.com/account/remotestorageapp/?appid=899770

Just for reference in case someone encounters a similar issue in the future.
Would be nice if the UI mentioned this behavior if possible.

**Comment by awsikei** [comment]
Hello, I ran into a problem just a few days ago. Almost no cloud opens for me, although everything worked fine a month ago. I tried all possible ways, but the maximum I could do was delete data from only one game. What could be the reason?
